export declare enum AppErrorCode {
    AUTHORIZATION_ERROR = "AUTHORIZATION_ERROR",
    FORM_VALIDATION_ERROR = "FORM_VALIDATION_ERROR",
    AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    RESOURCE_NOT_FOUND_ERROR = "RESOURCE_NOT_FOUND_ERROR"
}
